runtime: nodejs20
env: standard
service_account: capstone-bangkit-443012@appspot.gserviceaccount.com

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "firebase/serviceAccountKey.json"  # Ensure this path is correct
  BUCKET_NAME: "capstone-bangkit-443012.appspot.com"
  COMPUTE_ENGINE_URL: "http://34.101.101.12:5000"
  PORT: "8080"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

entrypoint: "./start.sh"